### ISSUE TITLE
arakoon_cluster_connect_master allocates timeout to multiple calls

### ISSUE THREAD

**Issue by redlicha** [openvstorage/crakoon#1]
The following happens in `arakoon_cluster_connect_master`:
* connect to arakoon instance(s sequentially)
* on a successful connection, query for the master
* connect to the returned master
.

The timeout passed covers all of these steps, so if contacting the first instance eats up the complete timeout (node down "tar pit"), retrieving the master info from another node will not work (as the remaining timeout is 0).

**Comment by wimpers** [comment]
from @redlicha 

```simply raising the timeout is not enough as then the first attempt will use up that longer timeout and not give the subsequent attempts with other cluster members enough / any time
at least asymptotically, with a badly tarpitted first node
so the simplest thing there is to give each node the same timeout - experimenting wiht that fixed my tests
so the fix for this isn't that much work actually
and the retrying to address the other issue mentioned in the associated voldrv-ee ticket also shouldn't be too hard
anyway, since carrying patches in volumedriver-buildtools{,-ee} against the incubaid repo becomes messy I figured it's best to clone the abandonded incubaid crakoon repo, also to track issues that way.

```

**Comment by wimpers** [comment]
From Arne

There's the `vregistry_arakoon_timeout_ms` key already. I could either add a related `vregistry_arakoon_no_master_retries` key or set the number of retries to a fixed value and based on that and the configured timeout feed the appropriate settings to (a yet-to-be-fixed) crakoon call.
